version: '2'
services:
  nextcloud:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  volume-php:
    scale: 1
    start_on_create: true
  volume-data:
    scale: 1
    start_on_create: true
  volume-config:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 800
        target_port: 800
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
catalog:
  name: nextcloud
  version: 0.0.2
  description: Private file sync and share server
  questions:
    - variable: HOST_PORT
      label: Port
      default: 80
      required: true
      type: int
    - variable: DB_PASSWORD
      label: MySQL password
      required: true
      type: password
    - variable: DATA_PATH
      label: Data path on host
      required: true
      type: string